name: loyalty_mobile_app
description: A Flutter mobile app for the Loyalty Engine API
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.1.1
  
  # HTTP Client
  dio: ^5.3.2
  
  # Local Storage
  shared_preferences: ^2.2.2
  
  # UI Components
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  
  # Navigation
  go_router: ^12.1.3
  
  # Utilities
  intl: ^0.18.1
  uuid: ^4.2.1
  
  # QR Code
  qr_flutter: ^4.1.0
  
  # Notifications
  flutter_local_notifications: ^16.3.0
  
  # Environment Variables
  flutter_dotenv: ^5.1.0
  
  # Color Picker
  flutter_colorpicker: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - env.example
  
  fonts:
    - family: RobotoFlex
      fonts:
        - asset: assets/fonts/RobotoFlex-VariableFont_GRAD,XOPQ,XTRA,YOPQ,YTAS,YTDE,YTFI,YTLC,YTUC,opsz,slnt,wdth,wght.ttf 